Repository tiago1820/proyecto-final-back, pull requests merged in 2024-01, with the labels that each got.

#8 Estructura del proyecto
  ESTRUCTURA.MD
  LICENSE
Labels: documentation

#16 Ruta People
  src/controllers/people/getPeople.controller.js
  src/db.js
  src/routes/index.js
  src/services/people/getPeople.service.js
Labels: enhancement

#24 Liitle bug
  index.js
  src/controllers/people/getPeopleFilter.controller.js
  src/services/people/getPeopleFilter.service.js
Labels: bug

#26 Documentacion con Swagger
  package-lock.json
  package.json
  src/app.js
  src/controllers/people/getPeople.controller.js
  src/routes/people.router.js
  src/swagger.js
Labels: documentation

#28 Fueron documentadas dos nuevas rutas
  ESTRUCTURA.MD
  src/controllers/people/getPeopleById.controller.js
  src/routes/people.router.js
Labels: documentation

#31 getPeopleOptions
  ESTRUCTURA.MD
  src/controllers/people/getPeopleOptions.controller.js
  src/routes/people.router.js
  src/services/people/getPeopleOptions.service.js
Labels: enhancement

#39 Geolocation
  src/controllers/geolocation/getMunicipalities.controller.js
  src/controllers/geolocation/getProvinces.controller.js
  src/routes/geolocation.router.js
  src/routes/index.js
  src/routes/people.router.js
  src/services/geolocation/getMunicipalities.service.js
  src/services/geolocation/getProvinces.service.js
  src/utils/formattedGeolocation.util.js
Labels: enhancement

#41 Swagger
  ESTRUCTURA.MD
  src/controllers/geolocation/getMunicipalities.controller.js
  src/controllers/people/postPeople.controller.js
  src/routes/categoriesRouter.js
  src/routes/geolocation.router.js
  src/routes/people.router.js
  src/services/geolocation/getMunicipalities.service.js
Labels: documentation

#43 agrega a people los campos averageRaking y countRanking
  src/models/people.js
  src/services/people/getPeople.service.js
  src/utils/formatPeople.js
  src/utils/validator.util.js
Labels: enhancement
